# Taps
tap 'homebrew/cask'
tap 'homebrew/bundle'

# Binaries
brew 'antibody'
brew 'coreutils' # Those that come with macOS are outdated
brew 'dialog' # Needed for SSHH (.dotfiles/bin/sshh)
brew 'nss' # Provides certutil
brew 'nano' # Text editor
brew 'topgrade' # Upgrade all software on computer
brew 'git'
brew 'tree' # List directories in a tree structure
brew 'htop'
brew 'ncdu' # Disk usage tool
brew 'fd' # Better find alternative
brew 'mole'

# Development *I'm not a developer anymore*
#brew 'php'
#brew 'symfony-cli'
#brew 'composer'
#brew 'node'
#brew 'nginx'
#brew 'm-cli' # CLI for managing macOS
#cask 'docker'
#cask 'jetbrains-toolbox'
cask 'visual-studio-code'

# Apps
cask 'rectangle'
cask 'nextcloud'
cask 'google-chrome'
cask 'firefox'
cask 'spotify'
cask 'protonmail-bridge'
cask '1password'
cask 'steam'
cask 'microsoft-office'
cask 'mullvad-vpn'
cask 'soulseek'
cask 'taskexplorer'
cask 'oversight'
cask 'iina'

# Messaging
cask 'whatsapp'
cask 'discord'
